import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Product } from '../../models/product.model';
import { ProductCardComponent } from '../product-card/product-card.component';

@Component({
  selector: 'app-product-list',
  standalone: true,
  imports: [CommonModule, ProductCardComponent],
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css',
})
export class ProductListComponent {
  // NOTE: images are local placeholders; links are real kaspi.kz pages.
  products: Product[] = [
    {
      id: 1,
      name: 'Apple iPhone 15 128GB',
      description: 'Popular iPhone 15 model. Demo catalog entry for Lab 4 Online Store.',
      price: 560254,
      rating: 4.9,
      image: 'assets/images/p1.jpg',
      images: ['assets/images/p1.jpg', 'assets/images/p2.jpg', 'assets/images/p3.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/2113002/review/?baseProductCode=&productCode=9800446&tabId=PRODUCT',
    },
    {
      id: 2,
      name: 'Apple iPhone 15 256GB',
      description: 'Same lineup with bigger storage. Demo catalog entry for Lab 4 Online Store.',
      price: 640000,
      rating: 4.8,
      image: 'assets/images/p2.jpg',
      images: ['assets/images/p2.jpg', 'assets/images/p1.jpg', 'assets/images/p3.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/6409007/address-tab/?merchantId=6409007&productCode=113137962&tabId=PRODUCT',
    },
    {
      id: 3,
      name: 'Apple AirPods Pro (2nd gen)',
      description: 'Noise cancelling wireless earbuds. Demo catalog entry for Lab 4 Online Store.',
      price: 129990,
      rating: 4.9,
      image: 'assets/images/p3.jpg',
      images: ['assets/images/p3.jpg', 'assets/images/p4.jpg', 'assets/images/p5.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/768012/review/?baseProductCode=&productCode=122962904&tabId=PRODUCT',
    },
    {
      id: 4,
      name: 'Apple AirPods 4',
      description: 'Wireless earbuds (demo item). Used to demonstrate list rendering and sharing.',
      price: 89990,
      rating: 4.7,
      image: 'assets/images/p4.jpg',
      images: ['assets/images/p4.jpg', 'assets/images/p3.jpg', 'assets/images/p5.jpg'],
      link: 'https://kaspi.kz/shop/m/8354001/products/?baseProductCode=&productCode=113398267&tabId=PRODUCT',
    },
    {
      id: 5,
      name: 'Dyson V15 Detect Absolute SV47',
      description: 'High-end cordless vacuum cleaner. Demo catalog entry for Lab 4 Online Store.',
      price: 379990,
      rating: 4.9,
      image: 'assets/images/p5.jpg',
      images: ['assets/images/p5.jpg', 'assets/images/p6.jpg', 'assets/images/p7.jpg'],
      link: 'https://kaspi.kz/shop/m/17532820/products/?baseProductCode=&productCode=116869079&tabId=PRODUCT',
    },
    {
      id: 6,
      name: 'Dyson Airwrap Co-Anda 2X',
      description: 'Hair styler (demo item). Used to demonstrate product cards and external links.',
      price: 373323,
      rating: 4.8,
      image: 'assets/images/p6.jpg',
      images: ['assets/images/p6.jpg', 'assets/images/p5.jpg', 'assets/images/p7.jpg'],
      link: 'https://kaspi.kz/shop/m/10428008/products?masterSku=3701306&merchantSku=3701306_738960859&productCode=3701306&tabId=PRODUCT',
    },
    {
      id: 7,
      name: 'Samsung Galaxy S24 5G 256GB',
      description: 'Flagship Samsung phone. Demo catalog entry for Lab 4 Online Store.',
      price: 543447,
      rating: 4.9,
      image: 'assets/images/p7.jpg',
      images: ['assets/images/p7.jpg', 'assets/images/p8.jpg', 'assets/images/p9.jpg'],
      link: 'https://kaspi.kz/shop/m/6873020/products?masterSku=123179842&merchantSku=123179842_074339968&productCode=123179842&tabId=PRODUCT',
    },
    {
      id: 8,
      name: 'Nintendo Switch OLED',
      description: 'Handheld console (demo item). Used for list rendering and share feature.',
      price: 159990,
      rating: 4.8,
      image: 'assets/images/p8.jpg',
      images: ['assets/images/p8.jpg', 'assets/images/p9.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/3132018/review/?baseProductCode=&productCode=102984631&tabId=PRODUCT',
    },
    {
      id: 9,
      name: 'Sony PlayStation 5 Slim Digital Bundle',
      description: 'Console bundle (demo item). Used to demonstrate external links to Kaspi.',
      price: 289990,
      rating: 4.8,
      image: 'assets/images/p9.jpg',
      images: ['assets/images/p9.jpg', 'assets/images/p8.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/30337913/address-tab/?baseProductCode=&merchantId=30337913&productCode=118721919&tabId=PRODUCT',
    },
    {
      id: 10,
      name: 'Apple MacBook Air 13 (2022) 16GB/256GB',
      description: 'Laptop (demo item). Used to satisfy 10+ real products and a responsive grid.',
      price: 543960,
      rating: 5.0,
      image: 'assets/images/p10.jpg',
      images: ['assets/images/p10.jpg', 'assets/images/p11.jpg', 'assets/images/p12.jpg'],
      link: 'https://kaspi.kz/shop/m/14626000/products/?baseProductCode=&productCode=118311630&tabId=PRODUCT',
    },
    {
      id: 11,
      name: 'Xiaomi Redmi Note (Kaspi listing)',
      description: 'Phone listing (demo item). Used to exceed the minimum 10 product requirement.',
      price: 199990,
      rating: 4.9,
      image: 'assets/images/p11.jpg',
      images: ['assets/images/p11.jpg', 'assets/images/p12.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/info/merchant/30358551/address-tab/?merchantId=30358551&productCode=123910518&tabId=PRODUCT',
    },
  ];
}