import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private readonly categories: Category[] = [
    { id: 1, name: 'Smartphones' },
    { id: 2, name: 'Headphones' },
    { id: 3, name: 'Laptops & Tablets' },
    { id: 4, name: 'Gaming & Consoles' },
  ];

  private readonly products: Product[] = [
    // Smartphones (5)
    {
      id: 1,
      name: 'Apple iPhone 15 128GB',
      description: 'Buy yourself an iPhone 15 for just 560k KZT!',
      price: 560254,
      rating: 4.9,
      image: 'assets/images/iphone15.jpg',
      images: ['assets/images/p1.jpg', 'assets/images/p2.jpg', 'assets/images/p3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-iphone-15-128gb-goluboi-113137929/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 2,
      name: 'Apple iPhone 16 256GB',
      description: 'Newest iPhone with 256GB storage.',
      price: 640000,
      rating: 4.8,
      image: 'assets/images/iphone16.jpg',
      images: ['assets/images/p2.jpg', 'assets/images/p1.jpg', 'assets/images/p3.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-iphone-16-128gb-zelenyi-123727574/?c=750000000',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 3,
      name: 'Samsung Galaxy S24 Ultra',
      description: 'Samsung flagship with powerful camera.',
      price: 599990,
      rating: 4.9,
      image: 'assets/images/galaxy-s24.jpg',
      images: ['assets/images/p3.jpg', 'assets/images/p4.jpg', 'assets/images/p5.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=samsung%20galaxy%20s24%20ultra',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 4,
      name: 'Xiaomi Redmi Note 13 Pro',
      description: 'Great balance of price and performance.',
      price: 199990,
      rating: 4.6,
      image: 'assets/images/redmi-note-13.jpg',
      images: ['assets/images/p4.jpg', 'assets/images/p5.jpg', 'assets/images/p6.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=redmi%20note%2013%20pro',
      categoryId: 1,
      likes: 0,
    },
    {
      id: 5,
      name: 'Google Pixel 8',
      description: 'Clean Android experience with great camera.',
      price: 349990,
      rating: 4.7,
      image: 'assets/images/pixel-8.jpg',
      images: ['assets/images/p5.jpg', 'assets/images/p6.jpg', 'assets/images/p7.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=google%20pixel%208',
      categoryId: 1,
      likes: 0,
    },

    // Headphones (5)
    {
      id: 6,
      name: 'Apple AirPods Pro (2nd gen)',
      description: 'AirPods are a MUST.',
      price: 129990,
      rating: 4.9,
      image: 'assets/images/airpods.jpg',
      images: ['assets/images/p3.jpg', 'assets/images/p4.jpg', 'assets/images/p5.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-generation-with-wireless-magsafe-charging-case-belyi-113677582/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 7,
      name: 'Apple AirPods 4',
      description: 'Coolest wireless AirPods.',
      price: 89990,
      rating: 4.7,
      image: 'assets/images/airpods4.jpg',
      images: ['assets/images/p4.jpg', 'assets/images/p3.jpg', 'assets/images/p5.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-4-belyi-124333372/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 8,
      name: 'Sony WH-1000XM4',
      description: 'Legendary noise-cancelling headphones.',
      price: 373323,
      rating: 4.8,
      image: 'assets/images/sony.jpg',
      images: ['assets/images/p6.jpg', 'assets/images/p5.jpg', 'assets/images/p7.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-sony-wh-1000xm4-serebristyi-100509735/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 9,
      name: 'Marshall Major IV',
      description: 'Iconic Marshall sound and design.',
      price: 543447,
      rating: 4.9,
      image: 'assets/images/marshall.jpg',
      images: ['assets/images/p7.jpg', 'assets/images/p8.jpg', 'assets/images/p9.jpg'],
      link: 'https://kaspi.kz/shop/p/naushniki-marshall-major-iv-jbl-clip-4-sinii-chernyi-131793119/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 10,
      name: 'JBL Tune 720BT',
      description: 'Comfortable wireless headphones with punchy bass.',
      price: 59990,
      rating: 4.5,
      image: 'assets/images/jbl-720.jpg',
      images: ['assets/images/p8.jpg', 'assets/images/p9.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=jbl%20tune%20720bt',
      categoryId: 2,
      likes: 0,
    },

    // Laptops & Tablets (5)
    {
      id: 11,
      name: 'Apple MacBook Air 13 (2022) 16GB/256GB',
      description: 'Perfect for study, work, and coffee shops.',
      price: 543960,
      rating: 5.0,
      image: 'assets/images/macbook.jpg',
      images: ['assets/images/p10.jpg', 'assets/images/p11.jpg', 'assets/images/p12.jpg'],
      link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2020-13-3-8-gb-ssd-256-gb-macos-mgn63ru-a-101182724/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 12,
      name: 'Apple MacBook Pro 14 M3',
      description: 'Powerful Pro notebook for creators.',
      price: 899990,
      rating: 4.9,
      image: 'assets/images/macbook-pro-14.jpg',
      images: ['assets/images/p11.jpg', 'assets/images/p12.jpg', 'assets/images/p13.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=macbook%20pro%2014%20m3',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 13,
      name: 'ASUS ROG Strix G15',
      description: 'Gaming laptop with high refresh display.',
      price: 679990,
      rating: 4.7,
      image: 'assets/images/asus-rog-g15.jpg',
      images: ['assets/images/p12.jpg', 'assets/images/p13.jpg', 'assets/images/p14.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=asus%20rog%20strix%20g15',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 14,
      name: 'Lenovo IdeaPad 3',
      description: 'Affordable everyday laptop.',
      price: 229990,
      rating: 4.4,
      image: 'assets/images/lenovo-ideapad-3.jpg',
      images: ['assets/images/p13.jpg', 'assets/images/p14.jpg', 'assets/images/p15.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=lenovo%20ideapad%203',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 15,
      name: 'Apple iPad 10.9 (10th gen)',
      description: 'Bright tablet for media and notes.',
      price: 289990,
      rating: 4.8,
      image: 'assets/images/ipad-10.jpg',
      images: ['assets/images/p14.jpg', 'assets/images/p15.jpg', 'assets/images/p16.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=ipad%2010%20gen',
      categoryId: 3,
      likes: 0,
    },

    // Gaming & Consoles (5)
    {
      id: 16,
      name: 'Nintendo Switch OLED',
      description: 'Portable console for gaming anywhere.',
      price: 159990,
      rating: 4.8,
      image: 'assets/images/nintendo.jpg',
      images: ['assets/images/p8.jpg', 'assets/images/p9.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=nintendo%20switch%20oled',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 17,
      name: 'Sony PlayStation 5 Slim Digital',
      description: 'Next‑gen gaming at home.',
      price: 289990,
      rating: 4.8,
      image: 'assets/images/sonypl.jpg',
      images: ['assets/images/p9.jpg', 'assets/images/p8.jpg', 'assets/images/p10.jpg'],
      link: 'https://kaspi.kz/shop/p/sony-playstation-5-slim-114696098/?c=750000000',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 18,
      name: 'Xbox Series X',
      description: '4K gaming powerhouse from Microsoft.',
      price: 279990,
      rating: 4.7,
      image: 'assets/images/xbox-series-x.jpg',
      images: ['assets/images/p15.jpg', 'assets/images/p16.jpg', 'assets/images/p17.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=xbox%20series%20x',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 19,
      name: 'Sony DualSense Controller',
      description: 'Extra controller for your PS5.',
      price: 39990,
      rating: 4.9,
      image: 'assets/images/dualsense.jpg',
      images: ['assets/images/p16.jpg', 'assets/images/p17.jpg', 'assets/images/p18.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=dualsense%20controller',
      categoryId: 4,
      likes: 0,
    },
    {
      id: 20,
      name: 'Nintendo Switch Pro Controller',
      description: 'Comfortable controller for longer sessions.',
      price: 49990,
      rating: 4.8,
      image: 'assets/images/switch-pro-controller.jpg',
      images: ['assets/images/p17.jpg', 'assets/images/p18.jpg', 'assets/images/p19.jpg'],
      link: 'https://kaspi.kz/shop/search/?text=nintendo%20switch%20pro%20controller',
      categoryId: 4,
      likes: 0,
    },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getProductsByCategory(categoryId: number): Product[] {
    return this.products.filter((p) => p.categoryId === categoryId);
  }
}
